name: Auto Update

on:
  # Trigger on push to main branch
  push:
    branches:
      - main
  
  # Trigger on schedule (daily at 2 AM UTC)
  schedule:
    - cron: '0 2 * * *'
  
  # Allow manual trigger
  workflow_dispatch:
    inputs:
      agent:
        description: 'Specific agent to run (architect, documenter, tester, security, janitor, or all)'
        required: false
        default: 'all'

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write
      issues: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Configure Git
        run: |
          git config --global user.name "ApsnyTravel AutoUpdate Bot"
          git config --global user.email "autoupdate@apsnytravel.com"
      
      - name: Run Auto Update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AGENT_MODE: ${{ github.event.inputs.agent || 'all' }}
        run: |
          echo "Running auto-update with agent mode: $AGENT_MODE"
          mkdir -p logs
          node scripts/autoupdate.js --agent=$AGENT_MODE --config=.autoupdate.yml
      
      - name: Commit and Push Changes
        run: |
          if [[ -n $(git status -s) ]]; then
            echo "Changes detected, committing..."
            git add .
            COMMIT_MSG="chore: automated update by autoupdate workflow"
            git commit -m "$COMMIT_MSG"
            git push origin main
            echo "Changes pushed successfully"
          else
            echo "No changes to commit"
          fi
      
      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: autoupdate-logs
          path: |
            .autoupdate.log
            .autoupdate_audit.log
            logs/
          retention-days: 30
      
      - name: Create Issue on Failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const title = '🚨 Auto Update Workflow Failed';
            const body = `The auto-update workflow failed on ${new Date().toISOString()}.
            
            **Workflow Run:** ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            
            Please review the logs and take appropriate action.`;
            
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: body,
              labels: ['autoupdate', 'bug']
            });
