name: Build

on:
  pull_request:
    branches: ["*"]
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  build:
    name: Build Verification
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run production build
        run: pnpm build

      - name: Check build output
        run: |
          if [ ! -d "dist" ]; then
            echo "❌ Build failed: dist directory not found"
            exit 1
          fi
          echo "✅ Build successful"

      - name: Check bundle size
        run: |
          DIST_SIZE=$(du -sh dist | cut -f1)
          echo "📦 Bundle size: $DIST_SIZE"

          # Check if dist size is reasonable (< 50MB)
          SIZE_BYTES=$(du -sb dist | cut -f1)
          MAX_SIZE=$((50 * 1024 * 1024))  # 50MB in bytes

          if [ $SIZE_BYTES -gt $MAX_SIZE ]; then
            echo "⚠️ Warning: Bundle size exceeds 50MB"
          else
            echo "✅ Bundle size is within acceptable limits"
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: github.ref == 'refs/heads/main'
        with:
          name: build-artifacts
          path: dist/
          retention-days: 7
